# Generated by Django 4.1.3 on 2022-11-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_user_employee_code_alter_user_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
